image: gcc

variables:
  GIT_DEPTH: 1
  BYOND_MAJOR: "512"
  BYOND_MINOR: "1454"
  BYOND_MACRO_COUNT: 2

job1:
  stage: deploy
  before_script:
    - dpkg --add-architecture i386
    - apt-get update
    - apt-get -y install libc6-i386
    - apt-get -y install libgcc1:i386
    - apt-get -y install libstdc++6:i386
    - chmod +x scripts/./install-byond.sh
    - scripts/./install-byond.sh
  script:
    - (num=`grep -E '\\\\(red|blue|green|black|italic|bold|b|i[^mc])' **/*.dm | wc -l`; echo "$num BYOND text macros (expecting ${BYOND_MACRO_COUNT} or fewer)"; [ $num -le ${BYOND_MACRO_COUNT} ])
    - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
    - bash scripts/dm.sh 44BR13.dme